[package]
name = "actus"
version = "0.1.0"
edition = "alpha"
entry = "main"

[dependencies]
fs = { path = "library/std" }
io = { path = "library/std" }
path = { path = "library/std" }

[build]
target = "host"
profile = "debug"
native_module = "actus"
position_independent = true
