[package]
name = "actus"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
cranelift-codegen = "0.135.2"
cranelift-frontend = "0.135.2"
cranelift-module = "0.135.2"
cranelift-native = "0.135.2"
cranelift-object = "0.135.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"

[dev-dependencies]
object = "0.39.1"

[[bench]]
name = "frontend"
harness = false
