mod analyzer;
mod borrowing;
mod call_arguments;
mod calls;
mod cleanup;
mod enum_registry;
mod enums;
mod errors;
mod intrinsics;
mod methods;
mod model;
mod ownership;
mod patterns;
mod scopes;
mod structs;
mod types;

pub use analyzer::analyze;
pub use cleanup::{CleanupAction, LoopExitKind, LoopUnwindPlan, ScopeCleanup, UnwindPlan};
pub use errors::{SemanticError, SemanticErrorKind};
pub use model::{Binding, BindingState, BorrowRecord, SemanticModel};
